### ISSUE TITLE
Allow --exclude-config arguments to be specified inside jar

### ISSUE THREAD

**Issue by philwebb** [paketo-buildpacks/native-image#196]
## Describe the Enhancement
Currently `--exclude-config` arguments can be specified in `BP_NATIVE_IMAGE_BUILD_ARGUMENTS` in order to pass a list of configurations that should be excluded during native image creation. Spring Boot is working on native image support and would like a way to define `--exclude-config` arguments inside the JAR file. This will allow a jar file to describe completely how it should be converted into a native image.

## Possible Solution
During creation of the JAR file, Spring Boot can add a `META-INF/native-image/exclude-config-args` file containing the `--exclude-config` arguments that it would like added. For example:

```
\Qfirst-library.jar\E ^/META-INF/native-image/.*
\Qsecond-library.jar\E ^/META-INF/native-image/.*
```

The file would consist of one line per `--exclude-config` argument. The example above would result in the following being passed to the `native-image` command line:

```
--exclude-config \Qfirst-library.jar\E ^/META-INF/native-image/.* --exclude-config \Qsecond-library.jar\E ^/META-INF/native-image/.*
```

## Motivation

Graal provides a [reachability-metadata](https://github.com/oracle/graalvm-reachability-metadata) repository that contains JSON files that allow third-party libraries to work. Spring Boot is looking to use this repository to bundle appropriate JSON files from the repository into the fat jar that it creates. We hope to achieve this by configuring the [native-build-tools](https://github.com/graalvm/native-build-tools) plugin so that it directly packages the appropriate JSON files. An enhancement request for native-build-tools [is currently under review](https://github.com/graalvm/native-build-tools/pull/322).

For most libraries, adding the metadata will be enough to create a fully functioning native image, however, some need to use "overrides". The [override flag](https://github.com/graalvm/native-build-tools/issues/268) allows the metadata repository to override hints that are packaged inside the library jar itself. It can be used when a library ships incorrect meta-data that later needs to be corrected.

When the native-build-tools plugin is being used directly to create the image it is able to construct appropriate `--exclude-config` arguments. For example, [this is how the Maven plugin generates the arguments](https://github.com/graalvm/native-build-tools/blob/82dd663a88181cfb71129ff9b8a033967e09cce2/native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/AbstractNativeMojo.java#L554-L556). We need an equivalent option for use with buildpacks and unfortunately we can use `--exclude-config` in the `Args` property under `META-INF/native-image/native-image.properties`.

For more background and discussion please see https://github.com/spring-projects/spring-boot/issues/31782

**Comment by sdeleuze** [comment]
@philwebb After discussing with @pivotal-david-osullivan this morning, we agreed that the easier path from a Buildpacks perspective would be for Spring Boot to generate a `META-INF/native-image/argfile` file that would directly contain the arguments to pass to the native-image like `--exclude-config \Qfirst-library.jar\E ^/META-INF/native-image/.* --exclude-config \Qsecond-library.jar\E ^/META-INF/native-image/.*`.

On buildpack side, it would then just be about detecting this well-known file and pass it to the native image compiler via `native-image @/path/to/META-INF/native-image/argfile`. That would also make this mechanism suitable for other arguments that need to be passed directly to the compiler.

Would you be ok with that solution?

**Comment by philwebb** [comment]
@sdeleuze Yes, sound good to me. I've opened https://github.com/spring-projects/spring-boot/issues/32738 and pushed a commit that should generate that file. We can't yet do an end-to-end test because we're waiting on an NBT release.

**Comment by sdeleuze** [comment]
As discussed today, end to end testing with Buildpacks should now be possible with NBT 0.9.15, even if we will need to release 0.9.16 to fix [this regression](https://github.com/graalvm/native-build-tools/issues/340) that should impact only local NBT usage.

**Comment by sdeleuze** [comment]
Works as expected, this issue can now be closed.
