### ISSUE TITLE
 builder-jammy-tiny fails to build spring-boot: permission denied

### ISSUE THREAD

**Issue by shineeng** [paketo-buildpacks/native-image#346]
I have a functioning spring-boot 3.3.3 service I'm trying to compile in native mode inside a podman container with the command:

`mvnw clean package -Pnative spring-boot:build-image -Ddocker.publishRegistry.username=%username% -Ddocker.publishRegistry.password=%password% -Ddocker.publishRegistry.url=https://workharbour`

The buildpack is pull and the compilation seems to be working. Sadly, the buildpack fails with a permission denied at the end:
```
[INFO]     [creator]        22.2s (9.3% of total time) in 1321 GCs | Peak RSS: 6.36GB | CPU load: 9.61
[INFO]     [creator]     --------------------------------------------------------------------------------
[INFO]     [creator]     Produced artifacts:
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/it.eng.silcloud.anagrafiche.AnagraficheApplication (executable)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/libawt.so (jdk_library)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/libawt_headless.so (jdk_library)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/libawt_xawt.so (jdk_library)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/libfontmanager.so (jdk_library)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/libfreetype.so (jdk_library)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/libjava.so (jdk_library_shim)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/libjavajpeg.so (jdk_library)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/libjvm.so (jdk_library_shim)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/liblcms.so (jdk_library)
[INFO]     [creator]     ================================================================================
[INFO]     [creator]     Finished generating 'it.pem.bimbam.anagrafiche.AnagraficheApplication' in 3m 57s.
[INFO]     [creator]       Removing bytecode
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to remove /workspace/BOOT-INF
[INFO]     [creator]     unlinkat /workspace/BOOT-INF: permission denied
[INFO]     [creator]     ERROR: failed to build: exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:58 min
```

## Expected Behavior
The image should be compiled and pushed

## Current Behavior
The buildpack fails with: `unlinkat /workspace/BOOT-INF: permission denied`

## Steps to Reproduce
Using Spring-boot 3.3.3 and paketobuildpacks/builder-jammy-tiny:latest

**Comment by shineeng** [comment]
I tried again after updating to podman 5.2.5 and the problem is the same. It looks like a permission error upon cleaning ?

**Comment by dmikusa** [comment]
You might check and see if podman exposes any properties or settings that you can use to control file permissions. Normally, at least with Docker, the file permissions will be inherited from your local file system. Thus if you `pack build -p foo/` the `/workspace` will have all the files with the same permissions as `foo/` locally.

It sounds like that's not the case here, which also sounds like something specific to Podman. I don't use that myself, so I really can't say why it's behaving that way, but there's not much we can do on the buildpack side. If the permissions on those files do not allow us to delete them, then we can't delete them and the build can't continue.

**Comment by shineeng** [comment]
thank you for your kind answer. I guess this ticket can be closed then

**Comment by dmikusa** [comment]
Feel free to update us when you get this sorted out. It's possible other people may hit this as well, podman is popular.

**Comment by shineeng** [comment]
yes, definitely. I cross posted it on stackoverflow [here ](https://stackoverflow.com/questions/79112977/spring-boot-buildpacks-fails-to-build-unlinkat-workspace-boot-inf-permission) and over docker it looks working
