### ISSUE TITLE
Remove requirement to set `start-class` which is Spring Boot related

### ISSUE THREAD

**Issue by dmikusa-pivotal** [paketo-buildpacks/native-image#83]
## What happened?

* What were you attempting to do?

If you try to build a non-Spring Boot app with native-image, it still expects `start-class` to be set, which is a Spring Boot convention.

```
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-bom-quarkus-platform-properties/2.1.2.Final/quarkus-bom-quarkus-platform-properties-2.1.2.Final.properties
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-bom-quarkus-platform-properties/2.1.2.Final/quarkus-bom-quarkus-platform-properties-2.1.2.Final.properties (90 B at 3.1 kB/s)
[INFO] [org.jboss.threads] JBoss Threads version 3.4.2.Final
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 2978ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28.923 s
[INFO] Finished at: 2021-08-16T15:08:57Z
[INFO] ------------------------------------------------------------------------
  Removing source code

Paketo Native Image Buildpack 4.2.0
  https://github.com/paketo-buildpacks/native-image
  Build Configuration:
    $BP_NATIVE_IMAGE                  true  enable native image build
    $BP_NATIVE_IMAGE_BUILD_ARGUMENTS        arguments to pass to the native-image command

Paketo Native Image Buildpack 4.2.0
  manifest does not contain Start-Class
ERROR: failed to build: exit status 1
Error: build failed
```

https://github.com/paketo-buildpacks/native-image/blob/main/native/build.go#L89-L94

* What did you expect to happen?

It should source this information from elsewhere if the app is not Spring Boot. Probably falling back to `main-class` (for runnable jars) or if that's not set either an env variable or default of "app-binary" or we could go old school and use "a.out".  Lol.

* What was the actual behavior? Please provide log output, if possible.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

TBS

* What buildpacks are you using? Please include versions.

native-image

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by vchrisb** [comment]
The native image buildpack is already expecting a `CLASSPATH` variable to be present, provided by a upstream buildpack. https://github.com/paketo-buildpacks/native-image/blob/906db7be8ff2fa702add3f4c5054293962e8723e/native/native_image.go#L76
I suggest doing something similar, e.g. expecting a `STARTCLASS` variable and fallback to looking for `start-class` and ultimately `main-class` in the manifest.
The spring boot buildpack, and potentially others, eventually should not only set `CLASSPATH` but additionally `STARTCLASS`.

**Comment by dmikusa-pivotal** [comment]
I have a PR for this. It relaxes the requirement and if `Start-Class` is not present, then it'll use `Main-Class`. I didn't go so far as to add an option to configure this value through an environment variable. We could potentially use a `BP_NATIVE_IMAGE_START_CLASS` (or something like that) but I'd want to see a use case for this first. Having `Main-Class` is pretty standard, so if that doesn't work I'd like to understand more about the cases where it's not sufficient. Thanks

**Comment by jjbustamante** [comment]
Hi @dmikusa-pivotal ,  I tried to use your PR to compile a custom Quarkus application that I have, also to compile the [getting started application](https://quarkus.io/guides/getting-started), but in both cases, I am having the following error:

![Screen Shot 2021-11-18 at 2 33 41 PM](https://user-images.githubusercontent.com/1181799/142485913-2f27ba0e-e0ba-4ae7-9c59-bd152bc6f3d9.png)

At first, I thought it was something related to my project, but then I also had the same error with the getting started application which is very simple.

**Comment by dmikusa-pivotal** [comment]
Ok @jjbustamante I believe that is progress. You're past this error and I believe onto the next problem, which is https://github.com/paketo-buildpacks/maven/issues/76

I suspect it's failing because it's missing some of the files from the Maven portion of the build. You could try to work around this by doing a Maven build locally and `pack build -p target/native-sources/`. That'll do a build from the given directory, which may allow native image to succeed. I haven't tried it though.

**Comment by jjbustamante** [comment]
Hi @dmikusa-pivotal. 

Let me summarize what I have done so far. 

1. I tried to work around the previous issue doing the Maven build locally and then invoking the pack CLI with `pack build -p target/native-sources/` ,  I am still facing the issue 
![Screen Shot 2021-11-22 at 9 55 23 AM](https://user-images.githubusercontent.com/1181799/142883178-3b7f9190-f04f-4c18-9481-fa3516a0aca7.png)

2. I downloaded the same `GraalVM` version to my local and tried to use a similar command the `native-image` buildpack is using to generate the native executable from the Quarkus sample application. That one is working, as we can see in the following image: 
![Screen Shot 2021-11-22 at 9 44 49 AM](https://user-images.githubusercontent.com/1181799/142882368-2bdbfdba-d96c-42cb-b254-506b8eeda6f3.png)
The command is similar (not exactly the same) but, the executable is created and I am able to run it.
![Screen Shot 2021-11-22 at 9 45 51 AM](https://user-images.githubusercontent.com/1181799/142882660-584d7b84-53d0-4c72-a578-81542e5cb465.png)

The difference of trying to build the application through pack vs my local is that is running on a container, but not sure what do if I have something on my local that can be affecting the build and not throwing the same error that I am facing when I use the `native-image` buildpack (which is what I am expecting)

**Comment by jjbustamante** [comment]
Ok, some news about my testing, I uncompressed the jar generated by Maven and tried to created native executable with that one and I got the same error from the  `native-image` Buildpack

![Screen Shot 2021-11-22 at 2 31 26 PM](https://user-images.githubusercontent.com/1181799/142923751-eb7a79e0-067b-4784-aeb9-5d68f70a0d42.png)

The problem is not actually a Buildpack issue, it seems to be related with the classpath and the libraries send to the `native-image` executable, if I do something like this: `native-image -cp getting-started-1.0.0-SNAPSHOT-runner.jar -cp lib/ io.quarkus.runner.GeneratedMain` it works, so I am not sure if there is something missing with the libraries, I will keep checking a little bit more

**Comment by jjbustamante** [comment]
@dmikusa-pivotal.

I think this PR is working fine, for what I tested the `Start-Class` is fixed, as you said, now we are facing the [maven 76 issue](https://github.com/paketo-buildpacks/maven/issues/76).
